const linkedIn='https://www.linkedin.com/in/zainab-ramzan-2397a2352';
const email='mailto:zainabramzan853@gmail.com';
const articlePressure='https://medium.com/@zainabramzan853/the-silent-pressure-to-succeed-in-your-20s-bdc181290156';
const articleShowUp='https://medium.com/@zainabramzan853/show-up-for-yourself-9baf79d90b7b';
const articleTech='https://medium.com/@zainabramzan853/technology-review-39bb7f03e052';
const projects=[
{name:'Artek',role:'Content Writer / Brand & Content Support',tag:'Brand communication · Blogs',image:'notebook.jpg',alt:'Notebook, pens, and coffee on a writing desk',description:'Social media and LinkedIn content, website blogs, and brand-focused writing for a UK-based company. My work includes six recent contributions to the Artek blog.',url:'https://www.arteksns.com/artek-blogs',label:'Explore the blog collection',scope:['Social media: captions and platform-specific messaging.','LinkedIn: professional posts and brand communication.','Blogs: structured content for the company website.'],more:'Writing across channels calls for a consistent brand voice, with the structure and tone adapted to each platform.'},
{name:'Shawais',role:'Website Content Writer',tag:'Website copy · Brand messaging',image:'workspace.jpg',alt:'Laptop and notebooks in a creative workspace',description:'Content across the company website, from service descriptions to brand messaging. The AI Solutions page is a focused example of explaining technical services to a business audience.',url:'https://shawais.com/ai-solutions/',label:'Read the AI Solutions page',scope:['Website copy and service descriptions.','Brand messaging that explains the company’s offering.','AI Solutions: capabilities, delivery approach, and business context.'],more:'My role was to make the company’s offerings understandable and give each page a clear message.',extra:'https://shawais.com/'},
{name:'TEDxSMIU',role:'Content Writer',tag:'Website · Social · LinkedIn',image:'library.jpg',alt:'Bookshelves in a sunlit library',description:'Website content, LinkedIn posts, and social media communication for TEDxSMIU. Writing adapted to the event’s public presence and the context of each platform.',url:'https://tedxsmiu.vercel.app/',label:'Explore the event website',scope:['Website: event communication and public-facing copy.','LinkedIn: professional event content.','Social media: captions and audience-facing messaging.'],more:'The focus is on bringing ideas to an audience with clarity, relevance, and an appropriate event voice.'},
{name:'Independent Writing',role:'Independent Content Writer & Personal Brand Writer',tag:'Editorial · Personal branding',image:'notebook.jpg',alt:'An open notebook and writing tools',description:'Personal stories, reflections, and technology writing on Medium, alongside my own LinkedIn and Substack presence and independent client work.',url:'https://medium.com/@zainabramzan853',label:'Explore my Medium writing',scope:['The Silent Pressure to Succeed in Your 20’s — February 2026.','Show up for yourself! — January 2026.','Is Technology Worth it? A complete Review — April 2024.'],more:'My independent writing gives me room to explore personal voice, build a narrative, and connect lived experience with a reader’s perspective.'},
{name:'UK-Based Student Projects',role:'Research & Professional Documentation Writer',tag:'Research · Documentation',image:'library.jpg',alt:'Rows of books in a research library',description:'Research-based documentation, structured reports, and project documentation supporting MS-level students in the UK. Confidential work is described here without publishing student details or private documents.',url:email+'?subject=Professional%20documentation%20enquiry',label:'Discuss documentation work',scope:['Organizing complex information into a clear structure.','Research-based documentation and professional reports.','Editing for clarity and a consistent professional or academic tone.'],more:'This work is confidential. I can discuss my approach and relevant experience without disclosing student or client material.'}
];
const external=(url,label,cls='text-link')=>`<a class="${cls}" href="${url}" ${url.startsWith('https')?'target="_blank" rel="noopener noreferrer"':''}>${label} <span aria-hidden="true">↗</span></a>`;
document.querySelector('#projects').innerHTML=projects.map((p,i)=>`<article class="project" id="project-${i+1}"><a class="project-media" href="${p.url}" ${p.url.startsWith('https')?'target="_blank" rel="noopener noreferrer"':''}><img src="${p.image}" alt="${p.alt}" loading="lazy" width="1400" height="934"><span class="image-caption">${p.name} <span aria-hidden="true">↗</span></span></a><div class="project-body"><div class="project-top"><span class="tags">${p.tag}</span><span class="number">0${i+1}</span></div><h3>${p.name}</h3><div class="role">${p.role}</div><p>${p.description}</p>${external(p.url,p.label)}${p.extra?'<br>'+external(p.extra,'View the full website'):''}<details><summary>Behind the work</summary><p>${p.more}</p><ul>${p.scope.map(s=>`<li>${s}</li>`).join('')}</ul></details></div></article>`).join('');
const samples=[
{title:'The Silent Pressure to Succeed in Your 20’s',cat:'Blogs',description:'A personal reflection on expectations, career uncertainty, and learning to choose a path.',role:'Writer',client:'Medium · February 2026',url:articlePressure,label:'Read article',kind:'Published article'},
{title:'Show up for yourself!',cat:'Blogs',description:'A personal story about university, growth, and committing to the person you want to become.',role:'Writer',client:'Medium · January 2026',url:articleShowUp,label:'Read article',kind:'Published article'},
{title:'Is Technology Worth it? A complete Review',cat:'Blogs',description:'An early piece exploring technology, connectivity, and their place in everyday life.',role:'Writer',client:'Medium · April 2024',url:articleTech,label:'Read article',kind:'Published article'},
{title:'AI Solutions',cat:'Website Content',description:'Explaining AI services, capabilities, and delivery to a business audience.',role:'Website Content Writer',client:'Shawais',url:'https://shawais.com/ai-solutions/',label:'Read website copy',kind:'Published page'},
{title:'Shawais website',cat:'Website Content',description:'Service descriptions and brand messaging across the company’s website.',role:'Website Content Writer',client:'Shawais',url:'https://shawais.com/',label:'View project',kind:'Published website'},
{title:'TEDxSMIU website',cat:'Website Content',description:'Event communication and website content for the university’s TEDx presence.',role:'Content Writer',client:'TEDxSMIU',url:'https://tedxsmiu.vercel.app/',label:'Read website copy',kind:'Published website'},
{title:'Artek blog collection',cat:'Blogs',description:'Career-focused company blogs. My contributions include six recent articles in this collection.',role:'Content Writer',client:'Artek',url:'https://www.arteksns.com/artek-blogs',label:'Browse the collection',kind:'Publication collection'},
{title:'Professional stories on LinkedIn',cat:'LinkedIn',description:'My own professional presence: personal branding, writing, and reflections on my journey.',role:'Personal Brand Writer',client:'My LinkedIn profile',url:linkedIn,label:'Visit LinkedIn',kind:'Public profile'},
{title:'Independent voice on Substack',cat:'Brand/Personal Branding',description:'Another home for my independent writing and personal perspective.',role:'Independent Writer',client:'Substack',url:'https://substack.com/@zainabramzan',label:'Visit Substack',kind:'Public profile'},
{title:'Personal branding on LinkedIn',cat:'Brand/Personal Branding',description:'How I present my experience, writing, and professional identity online.',role:'Personal Brand Writer',client:'LinkedIn',url:linkedIn,label:'Explore my profile',kind:'Public profile'},
{title:'My Instagram presence',cat:'Social Media',description:'Explore my personal social presence alongside my professional writing channels.',role:'Profile owner',client:'Instagram · @zainab_r148',url:'https://www.instagram.com/zainab_r148/',label:'Visit Instagram',kind:'Public profile'},
{title:'Research & professional documentation',cat:'Professional Documentation',description:'Research-based reports, project documentation, and clarity editing. Student and client documents remain confidential.',role:'Research & Documentation Writer',client:'UK-based student projects',url:'#project-5',label:'Read the work overview',kind:'Confidential work overview'}
];
const categories=['All','LinkedIn','Social Media','Blogs','Website Content','Brand/Personal Branding','Professional Documentation'];
const filters=document.querySelector('#filters');filters.innerHTML=categories.map((c,i)=>`<button type="button" aria-pressed="${i===0}" data-category="${c}">${c}</button>`).join('');
function render(category){const selected=samples.filter(s=>category==='All'||s.cat===category);document.querySelector('#count').textContent=`${selected.length} ${selected.length===1?'entry':'entries'} · ${category==='All'?'Articles, websites & writing channels':category}`;document.querySelector('#sample-grid').innerHTML=selected.map(s=>`<article class="sample"><div class="sample-top"><span class="tags">${s.cat}</span><span class="sample-kind">${s.kind}</span></div><h3>${s.title}</h3><p>${s.description}</p><div class="meta">${s.role}<br>${s.client}</div>${external(s.url,s.label)}</article>`).join('');}
filters.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;filters.querySelectorAll('button').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));render(b.dataset.category)});render('All');
const services=[['Social Media Content','Engaging captions, posts, content ideas, and platform-specific copy.'],['LinkedIn Content','Thought-leadership posts, personal branding, professional storytelling, and company content.'],['Blog & SEO Content','Structured, reader-friendly blogs shaped around search intent and audience needs.'],['Website Content','Clear website copy that communicates your brand’s value, services, and identity.'],['Brand & Personal Branding','A consistent voice that strengthens an individual’s or organization’s online presence.'],['Professional & Academic Documentation','Research-based documentation, structured reports, and written material for MS-level students and professional or academic projects.']];document.querySelector('#service-grid').innerHTML=services.map((s,i)=>`<article class="service"><span>0${i+1}</span><h3>${s[0]}</h3><p>${s[1]}</p></article>`).join('');
const steps=[
['Understand','Who are we speaking to?','Before choosing the words, I get clear on the audience, the platform, and the purpose. A LinkedIn post and a service page may share a message, but they need different approaches.','A clear brief'],
['Research','What does the reader need to know?','I explore the subject, relevant sources, audience needs, and the brand’s existing voice. The aim is to understand the idea well enough to explain it clearly.','An informed direction'],
['Structure','What should come first?','I organize the message around a useful opening, a logical flow, and a clear next step. Every paragraph has a job to do.','A purposeful outline'],
['Write','How should the message feel?','I shape the draft around the audience and brand voice, balancing personality with precision. The format serves the message, whether it’s a short caption or a detailed report.','A focused first draft'],
['Refine','Can this be clearer?','I revisit the draft for accuracy, consistency, rhythm, and unnecessary words. The final pass is about making it easier for the reader to understand and respond.','Content ready to communicate']
];
const controls=document.querySelector('#process-controls'),story=document.querySelector('#process-story');controls.innerHTML=steps.map((s,i)=>`<button type="button" data-step="${i}" aria-pressed="${i===0}" aria-controls="process-story"><span>0${i+1}</span>${s[0]}<span class="step-arrow" aria-hidden="true">↗</span></button>`).join('');
function showStep(i){const s=steps[i];controls.querySelectorAll('button').forEach((b,j)=>b.setAttribute('aria-pressed',String(i===j)));story.innerHTML=`<span class="process-number" aria-hidden="true">0${i+1}</span><div class="eyebrow">${s[0]} / ${i+1} OF 5</div><h3>${s[1]}</h3><p>${s[2]}</p><div class="process-outcome"><span>THE OUTCOME</span><strong>${s[3]}</strong></div>`;if(!matchMedia('(prefers-reduced-motion: reduce)').matches)story.animate([{opacity:.4,transform:'translateY(7px)'},{opacity:1,transform:'translateY(0)'}],{duration:300,easing:'ease-out'});}
controls.addEventListener('click',e=>{const b=e.target.closest('button');if(b)showStep(Number(b.dataset.step))});showStep(0);
const menu=document.querySelector('.menu'),nav=document.querySelector('header nav');menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));nav.classList.toggle('open',open)});nav.addEventListener('click',e=>{if(e.target.closest('a')){menu.setAttribute('aria-expanded','false');nav.classList.remove('open')}});document.addEventListener('keydown',e=>{if(e.key==='Escape'){menu.setAttribute('aria-expanded','false');nav.classList.remove('open')}});document.querySelector('#year').textContent=new Date().getFullYear();
const iconPaths={LinkedIn:'<rect x="3" y="3" width="18" height="18" rx="2"/><path d="M7 10v7M7 7v.1M11 17v-7m0 3c0-4 6-4 6 0v4"/>',Instagram:'<rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><path d="M17.5 6.5h.01"/>',Facebook:'<path d="M14 21v-9h3l.5-4H14V6c0-1 .5-2 2-2h2V1h-3c-4 0-5 3-5 5v2H7v4h3v9"/>',Substack:'<path d="M4 3h16M4 7h16M4 11h16v10l-8-5-8 5z"/>',Medium:'<ellipse cx="7" cy="12" rx="5" ry="7"/><ellipse cx="16" cy="12" rx="2" ry="7"/><path d="M22 6v12"/>'};
const socials=[['LinkedIn',linkedIn],['Instagram','https://www.instagram.com/zainab_r148/'],['Facebook','https://www.facebook.com/Zainab.ramzan.18/'],['Substack','https://substack.com/@zainabramzan'],['Medium','https://medium.com/@zainabramzan853']];
document.querySelector('#socials').innerHTML=socials.map(([name,url])=>`<a href="${url}" target="_blank" rel="noopener noreferrer" aria-label="Zainab on ${name}" title="${name}"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${iconPaths[name]}</svg><span class="social-tooltip">${name}</span></a>`).join('');
if('IntersectionObserver' in window){
const navObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){nav.querySelectorAll('a').forEach(a=>{if(a.hash==='#'+entry.target.id)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current')})}}),{rootMargin:'-15% 0px -55% 0px'});document.querySelectorAll('#home,#about,#services,#work,#samples,#contact').forEach(el=>navObserver.observe(el));
if(!matchMedia('(prefers-reduced-motion: reduce)').matches){const reveal=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.animate([{opacity:.35,transform:'translateY(20px)'},{opacity:1,transform:'translateY(0)'}],{duration:650,easing:'cubic-bezier(.2,.65,.3,1)'});reveal.unobserve(entry.target)}}),{threshold:.1});document.querySelectorAll('.section-top,.project,.feature,.service,.about-grid,.personal').forEach(el=>reveal.observe(el));}}
